### PR TITLE
Intern branch

### PR DESCRIPTION
**Pull request by sanchit94**

### CODE REVIEW

**Comment by atherdon** [comment]
can you rebase your commits - because right now we have a merge conflics?

**Comment by sanchit94** [comment]
@atherdon How do I do that?

I did the following,
```
git checkout intern-branch
git rebase master
```

**Comment by atherdon** [comment]
still not working.
google this `how to rebase branch with master`

**Comment by atherdon** [comment]
this is a good article: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by sanchit94** [comment]
@atherdon I have tried a few things but it doesn't seem to work. I have made some weird commits in doing so. The `git pull --rebase origin master` command ran successfully but still it is not fixed. Please suggest what to do.

**Comment by atherdon** [comment]
ok, i can fix it by hands, it's not a problem. i just wanted to generate some merge conflits in order to advance your git skills. but maybe this conflict cannot be rebased, don't know

**Comment by sanchit94** [comment]
@atherdon Yea I fixed it by keeping the latest versions in the **package-lock.json** file. Please check and merge!

**Comment by atherdon** [comment]
i'm ok to merge your pull request. but cann you add some commits - i'm testing a new automation software thing :)

**Comment by sanchit94** [comment]
Sure! :)

**Comment by atherdon** [comment]
Hmm, automatically bot not working :( maybe it'll catch out new pull request. will think about it later

**Pull request merged**
