### PR TITLE
Intern branch

### PR DESCRIPTION
**Pull request by atherdon**

### CODE REVIEW

**Comment by atherdon** [comment]
i think that create-react-app has jest inside the react-scripts.
can you try to uninstall jest that you've installed and just try `npm try jest` or add `"test2": "jest"`

**Comment by sanchit94** [comment]
Okay can we merge this now?

**Comment by sanchit94** [comment]
@atherdon This branch has no merge conflict, so it be merged. But I don't want to merge this. i want to merge development branch, but that is showing error. I don't know why?

**Comment by sanchit94** [comment]
I want to work for responsiveness of the calendar. Once this merge conflict is resolved and it is merged, I will start working on that

**Comment by atherdon** [comment]
@sanchit94 please create a new branch from `master` and name it `develop`, and it'll be our main branch for development. i think it'll reduce problems. later, when we'll understand that i merge everything well and we solved conflicts - we'll remove `intern-branch`

**Pull request merged**
