### PR TITLE
Enzyme install and test setup

### PR DESCRIPTION
**Pull request by sanchit94**

### CODE REVIEW

**Comment by sanchit94** [comment]
I've made a new branch development and I'll be working on this from now, intern-branch was messed up so I thought of creating a new one.  And why is this error when you merged my pull request #38

**Comment by atherdon** [comment]
@sanchit94 hehe this is what i wanted :) my evil plan.
i'm a big fan of practice, so you can learn git only when you broke it :) so i'm pretty happy that this situation rised. it was part of my plan to setup with you a git-flow approach

will finish some of my ongoing work and will check it.
Btw, this PR have errors too - take a look

**Comment by atherdon** [comment]
don't worry about error in build. it's just because we have a conlicts between brances

**Comment by sanchit94** [comment]
Okay, so we should resolve these errors as soon as possible. I will be writing tests for now, only reason it is taking so long is because it is boring. Should have gone with the test-first approach.

**Comment by sanchit94** [comment]
@atherdon Btw I don't have any errors in my local environment, just warnings that I have fixed. So this Travis CI error is just related to branch conflicts or deployment, right?

**Comment by atherdon** [comment]
For this error - yeah. Btw' you can read the build info by clicking on Details link(just to let you know)
But later we'll try to use this in order to understand if build working fine. will help us a lot

**Comment by atherdon** [comment]
ha - it's boring only now - when you'll realize how much time it save to
you later- you'll love it.
At January i spend about 3 days in order to find a small error. i use raven
try-catch coverage at a lot of places, but forget to cover a small amount
of code. it really drives me crazy - it crashed and i was not able to
figure out the main place ;)


On 03-Jul-2018 at 11:38 PM, Sanchit Sharma wrote:


Okay, so we should resolve these errors as soon as possible. I will be
writing tests for now, only reason it is taking so long is because it is
boring. Should have gone with the test-first approach.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/pull/56#issuecomment-402321260>,
or mute the thread

**Comment by sanchit94** [comment]
Yes I did go in the details section and logged into Travis CI using my github. Maybe adding .Travis file will help in development branch

**Comment by atherdon** [comment]
if you can check a master repo - you'll find out that we have travis
config here


On 04-Jul-2018 at 12:07 AM, Sanchit Sharma wrote:


Yes I did go in the details section and logged into Travis CI using my
github. Maybe adding .Travis file will help in development branch

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/pull/56#issuecomment-402325335>,
or mute the thread

**Comment by sanchit94** [comment]
Yes but it was not in my development branch. Maybe I branched it when `.travis.yml` file was not added. Anyways I have added the file.

**Pull request merged**
